services:
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: neon-local
    ports:
      - "5432:5432"
    env_file:
      - .env.development
  app:
    build:
      context: .
      target: dev
    container_name: acquisitions-app-dev
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - neon-local
